name: update-activity

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

env:
  GHLOG_VERSION: v0.1.0-alpha.1

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install ghlog
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: dhth/ghlog
          tag: ${{ env.GHLOG_VERSION }}
      - name: Run ghlog
        env:
          GHLOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ghlog run dhth \
            --limit 10 \
            --format markdown \
            > /tmp/activity.md
      - uses: actions/checkout@v7
      - name: Update README
        run: |
          python3 .github/scripts/update-activity.py /tmp/activity.md
      - name: Check if updates should be published
        id: check-publish
        run: |
          echo "publish=$(./.github/scripts/should-publish-results.sh)" >> "$GITHUB_OUTPUT"
      - name: Commit and push results
        if: steps.check-publish.outputs.publish == '1'
        run: |
          git config user.name "github-actions[bot]"
          # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update recent activity"
          git push
